# Conexión principal: Neon Tech (PostgreSQL)
# Configuración del servidor
quarkus.http.port=8080
quarkus.http.limits.max-body-size=50M

# Conexión principal: Neon Tech (PostgreSQL)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://ep-misty-morning-ae3mlpvr-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require
quarkus.datasource.username=neondb_owner
quarkus.datasource.password=npg_dP4lTUS8zLIx

# Hibernate ORM (Crea o actualiza las tablas automáticamente)
quarkus.hibernate-orm.schema-generation.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Perfil alternativo para MySQL Local (se activa con: -Dquarkus.profile=local)
%local.quarkus.datasource.db-kind=mysql
%local.quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/db_riesgo_sbp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
%local.quarkus.datasource.username=root
%local.quarkus.datasource.password=admin

# Configuración CORS oficial Quarkus 3
quarkus.http.cors.enabled=true
%dev.quarkus.http.cors.origins=/.*/
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

# Habilitar CORS para permitir peticiones desde Vercel y local
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=*
quarkus.http.cors.access-control-allow-credentials=false
quarkus.http.cors.access-control-max-age=24H